// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwUjtJWhPJbw2eycJ7axI0ek7MIHnen8',
    appId: '1:61072725067:web:2e915e4a322cd4c0f7a9ce',
    messagingSenderId: '61072725067',
    projectId: 'contact-2833f',
    authDomain: 'contact-2833f.firebaseapp.com',
    storageBucket: 'contact-2833f.firebasestorage.app',
    measurementId: 'G-B7ZBLTNE6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMgG9uZuTJvvDQXRs1_mRSpvw2wXNXKA',
    appId: '1:61072725067:android:a54cb1a7d93dd392f7a9ce',
    messagingSenderId: '61072725067',
    projectId: 'contact-2833f',
    storageBucket: 'contact-2833f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeEzeAUOHmod8YAdDf-K6C341EfQJNpf0',
    appId: '1:61072725067:ios:d908ea1231e85c4df7a9ce',
    messagingSenderId: '61072725067',
    projectId: 'contact-2833f',
    storageBucket: 'contact-2833f.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeEzeAUOHmod8YAdDf-K6C341EfQJNpf0',
    appId: '1:61072725067:ios:d908ea1231e85c4df7a9ce',
    messagingSenderId: '61072725067',
    projectId: 'contact-2833f',
    storageBucket: 'contact-2833f.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGwUjtJWhPJbw2eycJ7axI0ek7MIHnen8',
    appId: '1:61072725067:web:94652af6069a1fe4f7a9ce',
    messagingSenderId: '61072725067',
    projectId: 'contact-2833f',
    authDomain: 'contact-2833f.firebaseapp.com',
    storageBucket: 'contact-2833f.firebasestorage.app',
    measurementId: 'G-EQB3GZPLBF',
  );
}
